from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path, PurePosixPath

from app.models import CollectionAssignment


SLOT_RE = re.compile(r"_(\d{3})\.user\.2$", re.IGNORECASE)
COLOR_FILE_RE = re.compile(
    r"^(?P<prefix>esf\d{3}_\d{3}_cmd)(?:_(?:dx|ex))?_\d{3}\.user\.2$",
    re.IGNORECASE,
)
COLLECTION_IMAGE_NAME = "MyCustomCollection.png"
COLLECTION_MANIFEST_NAME = "sf6_color_collection_manifest.json"
COLLECTION_IMAGE_PATH = Path(__file__).resolve().parents[1] / "img" / COLLECTION_IMAGE_NAME


def export_collection_zip(
    output_path: str | Path,
    collection_name: str,
    assignments: list[CollectionAssignment],
) -> None:
    output_path = Path(output_path)
    root_name = output_path.stem if not collection_name else collection_name
    manifest_assignments = []

    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            f"{root_name}/modinfo.ini",
            "\n".join(
                (
                    f"name={root_name}",
                    "version=1.0",
                    "description=Generated by SF6 Color Collection Builder",
                    f"screenshot={COLLECTION_IMAGE_NAME}",
                    "author=Marshial",
                    "",
                )
            ),
        )
        if COLLECTION_IMAGE_PATH.exists():
            archive.write(
                COLLECTION_IMAGE_PATH,
                f"{root_name}/{COLLECTION_IMAGE_NAME}",
            )

        for assignment in assignments:
            with zipfile.ZipFile(assignment.source_zip) as source_zip:
                data = source_zip.read(assignment.source_internal_file_path)

            output_filename = rename_slot(
                PurePosixPath(assignment.source_internal_file_path).name,
                assignment.target_slot,
                assignment.type,
            )
            output_internal_path = (
                f"{root_name}/natives/stm/product/model/esf/"
                f"{assignment.character}/{assignment.costume}/{output_filename}"
            )
            archive.writestr(output_internal_path, data)
            manifest_assignments.append(
                {
                    "character": assignment.character,
                    "costume": assignment.costume,
                    "type": assignment.type,
                    "target_slot": assignment.target_slot,
                    "exported_internal_file_path": output_internal_path,
                    "source_slot": assignment.source_slot,
                    "source_mod_name": assignment.source_mod_name,
                }
            )

        archive.writestr(
            f"{root_name}/{COLLECTION_MANIFEST_NAME}",
            json.dumps(
                {
                    "format": "sf6-color-collection",
                    "version": 1,
                    "collection_name": root_name,
                    "assignments": manifest_assignments,
                },
                indent=2,
            ),
        )


def rename_slot(filename: str, target_slot: str, target_type: str | None = None) -> str:
    lowered = filename.lower()
    match = COLOR_FILE_RE.match(lowered)
    if not match:
        return SLOT_RE.sub(f"_{target_slot}.user.2", lowered)

    if target_type is None:
        type_match = re.search(r"_cmd_(dx|ex)_", lowered)
        target_type = type_match.group(1) if type_match else "normal"
    type_segment = "" if target_type == "normal" else f"_{target_type}"
    return f"{match.group('prefix')}{type_segment}_{target_slot}.user.2"
