from __future__ import annotations

import json
import re
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from app.models import CollectionAssignment


SLOT_RE = re.compile(r"_(\d{3})\.user\.2$", re.IGNORECASE)
COLOR_FILE_RE = re.compile(
    r"^(?P<prefix>esf\d{3}_\d{3}_cmd)(?:_(?:dx|ex))?_\d{3}\.user\.2$",
    re.IGNORECASE,
)
COLLECTION_IMAGE_NAME = "MyCustomCollection.png"
COLLECTION_MANIFEST_NAME = "sf6_color_collection_manifest.json"
COLLECTION_IMAGE_PATH = Path(__file__).resolve().parents[1] / "img" / COLLECTION_IMAGE_NAME
EDITED_DESCRIPTION_MARKER = "*Edited by Color Collection Builder"
PREVIEW_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp"}


@dataclass(frozen=True)
class ExistingZipMetadata:
    modinfo_path: str | None
    modinfo_data: bytes | None
    preview_files: dict[str, bytes]


def export_collection_zip(
    output_path: str | Path,
    collection_name: str,
    assignments: list[CollectionAssignment],
    preserve_existing_metadata: bool = False,
    modinfo_fields: dict[str, str] | None = None,
    preview_image_path: str | Path | None = None,
) -> None:
    output_path = Path(output_path)
    root_name = output_path.stem if not collection_name else collection_name
    source_payloads = [
        (assignment, _read_assignment_data(assignment))
        for assignment in assignments
    ]
    existing_metadata = (
        _read_existing_zip_metadata(output_path)
        if preserve_existing_metadata
        and output_path.exists()
        and modinfo_fields is None
        and preview_image_path is None
        else ExistingZipMetadata(None, None, {})
    )
    manifest_assignments = []

    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        if modinfo_fields is not None:
            preview_name = _preview_archive_name(preview_image_path)
            fields = _normalized_modinfo_fields(root_name, modinfo_fields, preview_name)
            archive.writestr(
                f"{root_name}/modinfo.ini",
                "\n".join(f"{key}={value}" for key, value in fields.items()) + "\n",
            )
        elif existing_metadata.modinfo_path and existing_metadata.modinfo_data:
            archive.writestr(
                existing_metadata.modinfo_path,
                existing_metadata.modinfo_data,
            )
        else:
            archive.writestr(
                f"{root_name}/modinfo.ini",
                "\n".join(
                    (
                        f"name={root_name}",
                        "version=1.0",
                        "description=Generated by SF6 Color Collection Builder",
                        f"screenshot={COLLECTION_IMAGE_NAME}",
                        "author=Marshial",
                        "",
                    )
                ),
            )

        if preview_image_path:
            preview_path = Path(preview_image_path)
            if preview_path.exists():
                archive.write(preview_path, f"{root_name}/{preview_path.name}")
        elif existing_metadata.preview_files:
            for image_path, image_data in existing_metadata.preview_files.items():
                archive.writestr(image_path, image_data)
        elif COLLECTION_IMAGE_PATH.exists():
            archive.write(
                COLLECTION_IMAGE_PATH,
                f"{root_name}/{COLLECTION_IMAGE_NAME}",
        )

        for assignment, data in source_payloads:
            output_filename = rename_slot(
                PurePosixPath(assignment.source_internal_file_path).name,
                assignment.target_slot,
                assignment.type,
            )
            output_internal_path = (
                f"{root_name}/natives/stm/product/model/esf/"
                f"{assignment.character}/{assignment.costume}/{output_filename}"
            )
            archive.writestr(output_internal_path, data)
            manifest_assignments.append(
                {
                    "character": assignment.character,
                    "costume": assignment.costume,
                    "type": assignment.type,
                    "target_slot": assignment.target_slot,
                    "exported_internal_file_path": output_internal_path,
                    "source_slot": assignment.source_slot,
                    "source_mod_name": assignment.source_mod_name,
                    "source_kind": assignment.source_kind,
                }
            )

        archive.writestr(
            f"{root_name}/{COLLECTION_MANIFEST_NAME}",
            json.dumps(
                {
                    "format": "sf6-color-collection",
                    "version": 1,
                    "collection_name": root_name,
                    "assignments": manifest_assignments,
                },
                indent=2,
            ),
        )


def _read_assignment_data(assignment: CollectionAssignment) -> bytes:
    if assignment.source_kind == "folder":
        return (assignment.source_zip / assignment.source_internal_file_path).read_bytes()
    with zipfile.ZipFile(assignment.source_zip) as source_zip:
        return source_zip.read(assignment.source_internal_file_path)


def _preview_archive_name(preview_image_path: str | Path | None) -> str:
    if preview_image_path:
        return Path(preview_image_path).name
    return COLLECTION_IMAGE_NAME


def _normalized_modinfo_fields(
    root_name: str,
    modinfo_fields: dict[str, str],
    preview_name: str,
) -> dict[str, str]:
    fields = {
        key.strip().lower(): value.strip()
        for key, value in modinfo_fields.items()
        if key.strip() and value.strip()
    }
    fields.setdefault("name", root_name)
    fields.setdefault("version", "1.0")
    fields.setdefault("description", "Generated by SF6 Color Collection Builder")
    fields.setdefault("author", "Marshial")
    if not any(key in fields for key in ("screenshot", "image", "preview")):
        fields["screenshot"] = preview_name
    return fields


def _read_existing_zip_metadata(output_path: Path) -> ExistingZipMetadata:
    modinfo_path: str | None = None
    modinfo_data: bytes | None = None
    preview_files: dict[str, bytes] = {}
    try:
        with zipfile.ZipFile(output_path) as archive:
            names = [name for name in archive.namelist() if not name.endswith("/")]
            for name in names:
                pure_name = PurePosixPath(name)
                if pure_name.name.lower() == "modinfo.ini" and modinfo_path is None:
                    modinfo_path = name
                    modinfo_data = _append_edited_marker(archive.read(name))
                elif pure_name.suffix.lower() in PREVIEW_IMAGE_SUFFIXES:
                    preview_files[name] = archive.read(name)
    except (OSError, zipfile.BadZipFile):
        return ExistingZipMetadata(None, None, {})
    return ExistingZipMetadata(modinfo_path, modinfo_data, preview_files)


def _append_edited_marker(modinfo_data: bytes) -> bytes:
    text = modinfo_data.decode("utf-8-sig", errors="replace")
    lines = text.splitlines()
    output_lines: list[str] = []
    changed = False

    for line in lines:
        key, separator, value = line.partition("=")
        if separator and key.strip().lower() == "description":
            if EDITED_DESCRIPTION_MARKER not in value:
                line = f"{key}{separator}{value.rstrip()} {EDITED_DESCRIPTION_MARKER}"
            changed = True
        output_lines.append(line)

    if not changed:
        output_lines.append(f"description={EDITED_DESCRIPTION_MARKER}")

    return ("\n".join(output_lines) + "\n").encode("utf-8")


def rename_slot(filename: str, target_slot: str, target_type: str | None = None) -> str:
    lowered = filename.lower()
    match = COLOR_FILE_RE.match(lowered)
    if not match:
        return SLOT_RE.sub(f"_{target_slot}.user.2", lowered)

    if target_type is None:
        type_match = re.search(r"_cmd_(dx|ex)_", lowered)
        target_type = type_match.group(1) if type_match else "normal"
    type_segment = "" if target_type == "normal" else f"_{target_type}"
    return f"{match.group('prefix')}{type_segment}_{target_slot}.user.2"
